name: deploy-to-development

on:
  push:
    branches:
      - development


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Development Environment
        run: echo "Deploying to Development Environment..."